# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgpdb.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PGPKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField()),
                ('file', models.FileField(upload_to=pgpdb.models._pgp_key_model_upload_to)),
                ('crc24', models.CharField(max_length=4)),
                ('is_revoked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PGPPublicKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('is_sub', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField()),
                ('expiration_time', models.DateTimeField(null=True)),
                ('algorithm', models.IntegerField(choices=[(0, 'Unknown'), (1, 'RSA (Encrypt or Sign)'), (2, 'RSA Encrypt-Only'), (3, 'RSA Sign-Only'), (16, 'Elgamal (Encrypt-Only)'), (17, 'DSA (Digital Signature Algorithm)'), (18, 'ECDH public key algorithm'), (19, 'ECDSA public key algorithm'), (20, 'formerly Elgamal Encrypt or Sign'), (21, 'Diffie-Hellman')], default=0)),
                ('bits', models.IntegerField()),
                ('fingerprint', models.CharField(max_length=40)),
                ('keyid', models.CharField(max_length=16)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_keys', to='pgpdb.PGPKeyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PGPSignatureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('type', models.IntegerField(choices=[(-1, 'Unknown'), (0, 'Binary'), (1, 'Text'), (2, 'Standalone'), (16, 'Key General'), (17, 'Key Personal'), (18, 'Key Casual'), (19, 'Key Personal'), (24, 'Binding'), (31, 'Direct'), (32, 'Key Revoke'), (40, 'SubKey Revoke'), (48, 'ID Revoke'), (64, 'Timestamp')], default=-1)),
                ('pka', models.IntegerField(choices=[(0, 'Unknown'), (1, 'RSA (Encrypt or Sign)'), (2, 'RSA Encrypt-Only'), (3, 'RSA Sign-Only'), (16, 'Elgamal (Encrypt-Only)'), (17, 'DSA (Digital Signature Algorithm)'), (18, 'ECDH public key algorithm'), (19, 'ECDSA public key algorithm'), (20, 'formerly Elgamal Encrypt or Sign'), (21, 'Diffie-Hellman')], default=0)),
                ('hash', models.IntegerField(choices=[(0, 'Unknown'), (1, 'MD5'), (2, 'SHA1'), (3, 'RIPEMD160'), (4, 'Reserved (4)'), (5, 'Reserved (5)'), (6, 'Reserved (6)'), (7, 'Reserved (7)'), (8, 'SHA256'), (9, 'SHA384'), (10, 'SHA512'), (11, 'SHA224')], default=0)),
                ('creation_time', models.DateTimeField()),
                ('expiration_time', models.DateTimeField(null=True)),
                ('keyid', models.CharField(max_length=16)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='pgpdb.PGPKeyModel')),
                ('pkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='pgpdb.PGPPublicKeyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PGPUserIDModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('userid', models.TextField()),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userids', to='pgpdb.PGPKeyModel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pgpsignaturemodel',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='pgpdb.PGPUserIDModel'),
        ),
    ]
